"use client";

import { useMemo, useState } from "react";

const diseases = [
"Kejang demam","Tetanus","HIV AIDS tanpa komplikasi","Tension headache","Migren","Bell’s palsy","Vertigo (Benign paroxysmal positional vertigo)","Gangguan somatoform","Insomnia","Benda asing di konjungtiva","Konjungtivitis","Perdarahan subkonjungtiva","Mata kering","Blefaritis","Hordeolum","Trikiasis","Episkleritis","Hipermetropia ringan","Miopia ringan","Astigmatism ringan","Presbiopia","Buta senja","Otitis eksterna","Otitis media akut","Serumen prop","Mabuk perjalanan","Furunkel pada hidung","Rhinitis akut","Rhinitis vasomotor","Rhinitis alergika","Benda asing","Epistaksis","Influenza","Pertusis","Faringitis","Tonsilitis","Laringitis","Asma bronchial","Bronkitis akut","Pneumonia, bronkopneumonia","Tuberkulosis paru tanpa komplikasi","Hipertensi esensial","Kandidiasis mulut","Ulkus mulut (aptosa, herpes)","Parotitis","Infeksi pada umbilicus","Gastritis","Gastroenteritis (termasuk kolera, giardiasis)","Refluks gastroesofagus","Demam tifoid","Intoleransi makanan","Alergi makanan","Keracunan makanan","Penyakit cacing tambang","Strongiloidiasis","Askariasis","Skistosomiasis","Taeniasis","Hepatitis A","Disentri basiler, disentri amuba","Hemoroid grade 1/2","Infeksi saluran kemih","Gonore","Pielonefritis tanpa komplikasi","Fimosis","Parafimosis","Sindrom duh (discharge) genital (gonore dan nongonore)","Infeksi saluran kemih bagian bawah","Vulvitis","Vaginitis","Vaginosis bakterialis","Salpingitis","Kehamilan normal","Aborsi spontan komplit","Anemia defisiensi besi pada kehamilan","Ruptur perineum tingkat 1/2","Abses folikel rambut atau kelenjar sebasea","Mastitis","Cracked nipple","Inverted nipple","Diabetes melitus tipe 1","Diabetes melitus tipe 2","Hipoglikemia ringan","Malnutrisi energi-protein","Defisiensi vitamin","Defisiensi mineral","Dislipidemia","Hiperurisemia","Obesitas","Anemia defisiensi besi","Limfadenitis","Demam dengue, DHF","Malaria","Leptospirosis (tanpa komplikasi)","Reaksi anafilaktik","Ulkus pada tungkai","Lipoma","Veruka vulgaris","Moluskum kontagiosum","Herpes zoster tanpa komplikasi","Morbili tanpa komplikasi","Varisela tanpa komplikasi","Herpes simpleks tanpa komplikasi","Impetigo","Impetigo ulseratif (ektima)","Folikulitis superfisialis","Furunkel, karbunkel","Eritrasma","Erisipelas","Skrofuloderma","Lepra","Sifilis stadium 1 dan 2","Tinea kapitis","Tinea barbe","Tinea fasialis","Tinea korporis","Tinea manus","Tinea unguium","Tinea kruris","Tinea pedis","Pitiriasis vesikolor","Kandidosis mukokutan ringan","Cutaneus larva migran","Filariasis","Pedikulosis kapitis","Pedikulosis pubis","Skabies","Reaksi gigitan serangga","Dermatitis kontak iritan","Dermatitis atopik (kecuali recalcitrant)","Dermatitis numularis","Napkin eczema","Dermatitis seboroik","Pitiriasis rosea","Akne vulgaris ringan","Hidradenitis supuratif","Dermatitis perioral","Miliaria","Urtikaria akut","Exanthematous drug eruption, fixed drug eruption","Vulnus laseratum, punctum","Luka bakar derajat 1 dan 2","Kekerasan tumpul","Kekerasan tajam"
];

const detail: Record<string, { diagnosis:string; workup:string; differential:string; management:string; followUp:string; referral:string }> = {
"Kejang demam": { diagnosis:"Kejang pada anak 6–60 bulan yang berhubungan dengan demam setelah penyebab intrakranial lain tidak mendukung; klasifikasikan sederhana vs kompleks.", workup:"Anamnesis durasi/fokalitas, sumber demam, imunisasi, obat/toksin dan pemeriksaan neurologis. LP/lab tidak rutin kecuali ada indikasi klinis.", differential:"Meningitis/ensefalitis, epilepsi, hipoglikemia, gangguan elektrolit, sinkop/rigors.", management:"ABC, posisi aman, terapi kejang berkepanjangan sesuai protokol kegawatdaruratan, tata laksana sumber demam dan edukasi orang tua. Antikejang jangka panjang umumnya tidak rutin pada kejang demam sederhana.", followUp:"Edukasi pertolongan pertama, pencatatan durasi kejang dan tanda bahaya. Evaluasi ulang bila kompleks atau terdapat kejang tanpa demam.", referral:"Segera bila kejang >5 menit/berulang tanpa pulih, fokal, kesadaran tidak pulih, tanda infeksi SSP, atau penyebab sekunder dicurigai." },
"Asma bronchial": { diagnosis:"Gejala respirasi yang bervariasi seperti mengi, sesak, batuk atau rasa berat dada dengan bukti variabilitas hambatan aliran udara bila tersedia.", workup:"Spirometri dengan uji bronkodilator bila memungkinkan; evaluasi pencetus, komorbid dan diagnosis banding.", differential:"COPD, disfungsi laring, infeksi, gagal jantung, benda asing dan penyebab sesak lain.", management:"Terapi pengontrol/pelega berdasarkan tingkat kontrol dan guideline asma terbaru; edukasi teknik inhaler, kepatuhan dan rencana aksi. Eksaserbasi ditangani segera sesuai derajat berat.", followUp:"Nilai kontrol gejala, fungsi paru, teknik inhaler, kepatuhan dan eksaserbasi; lakukan step-up/step-down sesuai kontrol.", referral:"Serangan berat, respons buruk, hipoksemia, kelelahan napas, penurunan kesadaran atau diagnosis tidak jelas." },
"Pneumonia, bronkopneumonia": { diagnosis:"Infeksi saluran napas bawah dengan tanda klinis pneumonia; tentukan derajat berat berdasarkan tanda bahaya, oksigenasi dan kondisi umum.", workup:"Pulse oximetry bila tersedia; pemeriksaan tambahan berdasarkan derajat berat. Foto toraks tidak rutin untuk semua kasus rawat jalan ringan.", differential:"Bronkitis, asma, bronkiolitis, TB, aspirasi, gagal jantung dan infeksi virus lain.", management:"Tentukan rawat jalan vs rawat inap. Suportif termasuk oksigen bila hipoksemia dan hidrasi adekuat; antibiotik bila etiologi bakteri dicurigai, sesuai guideline lokal.", followUp:"Pantau respons, demam, napas, hidrasi dan saturasi. Edukasi tanda bahaya dan kepatuhan terapi.", referral:"Hipoksemia, distress napas berat, sepsis, gangguan kesadaran, dehidrasi berat, gagal terapi atau komplikasi." },
"Otitis media akut": { diagnosis:"Gejala akut dengan temuan telinga tengah yang mendukung, misalnya bulging membran timpani/efusi dengan inflamasi; jangan menegakkan diagnosis hanya dari otalgia.", workup:"Otoskopi adalah pemeriksaan utama; pemeriksaan tambahan tidak rutin tanpa komplikasi.", differential:"Otitis eksterna, efusi telinga tengah, benda asing, trauma dan nyeri rujukan.", management:"Analgesia penting. Keputusan antibiotik bergantung usia, berat gejala, unilateral/bilateral, otore dan kemampuan follow-up sesuai guideline pediatrik.", followUp:"Evaluasi perbaikan dan tanda komplikasi; evaluasi pendengaran bila efusi menetap atau ada gangguan pendengaran.", referral:"Mastoiditis, kelumpuhan nervus fasialis, komplikasi intrakranial, kondisi berat atau gagal terapi/rekurensi." },
"Gastroenteritis (termasuk kolera, giardiasis)": { diagnosis:"Diare akut/muntah dengan penilaian derajat dehidrasi dan pencarian tanda penyakit invasif.", workup:"Fokus pada status hidrasi; pemeriksaan feses/lab dipilih pada darah di feses, penyakit berat, wabah, imunokompromais atau diare persisten.", differential:"Disentri, kolera, parasitosis, IBD, malabsorpsi dan intoksikasi makanan.", management:"Rehidrasi oral untuk dehidrasi ringan-sedang; IV bila syok/dehidrasi berat atau gagal oral. Lanjutkan nutrisi. Antibiotik/antiparasit hanya bila indikasi etiologis jelas.", followUp:"Pantau asupan, muntah, diare, urin dan berat badan. Edukasi higiene, keamanan makanan dan tanda bahaya.", referral:"Syok, dehidrasi berat, gangguan kesadaran, perdarahan GI, nyeri hebat, sepsis atau gagal rehidrasi oral." },
"Demam dengue, DHF": { diagnosis:"Demam akut yang konsisten dengan dengue berdasarkan klinis dan epidemiologi; nilai tanda peringatan, kebocoran plasma, perdarahan dan keterlibatan organ.", workup:"Serial tanda vital, status hidrasi, hematokrit/trombosit sesuai fase; pemeriksaan diagnostik dipilih berdasarkan hari sakit dan ketersediaan.", differential:"Malaria, tifoid, chikungunya, leptospirosis, infeksi virus lain dan sepsis.", management:"Monitoring dan terapi cairan terukur sesuai fase adalah inti tata laksana. Hindari NSAID karena risiko perdarahan. Kenali fase kritis dan tanda peringatan.", followUp:"Pantau perfusi, diuresis, hematokrit, trombosit dan tanda kebocoran sesuai fase; edukasi kapan harus kembali segera.", referral:"Tanda peringatan, syok, perdarahan bermakna, gangguan organ, komorbid berat atau monitoring tidak adekuat." },
"Diabetes melitus tipe 2": { diagnosis:"Konfirmasi dengan kriteria glukosa/HbA1c yang berlaku dan pastikan klasifikasi tipe diabetes benar.", workup:"Evaluasi tekanan darah, berat badan, lipid, fungsi ginjal/albuminuria, kaki, mata dan risiko kardiovaskular.", differential:"DM tipe 1, diabetes sekunder/monogenik, hiperglikemia akibat obat dan penyakit endokrin.", management:"Gaya hidup dan edukasi sebagai fondasi. Farmakoterapi dipilih menurut tingkat hiperglikemia, komorbid kardiorenal, berat badan, risiko hipoglikemia, biaya dan guideline terbaru.", followUp:"Pantau HbA1c/glukosa, tekanan darah, lipid, ginjal, kaki, mata, kepatuhan dan hipoglikemia.", referral:"Krisis hiperglikemia, hipoglikemia berat berulang, komplikasi progresif, kehamilan, diagnosis tidak jelas atau target tidak tercapai." }
};

function makeDetail(name:string){ return detail[name] ?? { diagnosis:`Tegakkan diagnosis ${name} berdasarkan anamnesis, pemeriksaan fisik dan kriteria diagnostik terbaru; selalu singkirkan red flags dan diagnosis yang mengancam nyawa.`, workup:`Pilih pemeriksaan penunjang secara selektif berdasarkan derajat berat, usia, komorbiditas dan diagnosis banding. Hindari pemeriksaan yang tidak mengubah tata laksana.`, differential:`Susun diagnosis banding berdasarkan onset, gejala, tanda fisik, sistem organ dan red flags.`, management:`Stabilisasi ABC bila diperlukan, berikan terapi suportif dan terapi spesifik sesuai etiologi. Obat, dosis, durasi dan target harus mengikuti pedoman nasional/internasional terbaru serta kondisi pasien.`, followUp:`Nilai respons terapi, kepatuhan, efek samping dan komplikasi; berikan edukasi perjalanan penyakit serta tanda bahaya.`, referral:`Rujuk bila tidak stabil, terdapat red flags/komplikasi, diagnosis tidak pasti, gagal terapi awal, atau kebutuhan tindakan/fasilitas melebihi kompetensi layanan primer.`}; }

export default function Skdi4aPage(){
 const [q,setQ]=useState(""); const [selected,setSelected]=useState(diseases[0]);
 const filtered=useMemo(()=>diseases.filter(x=>x.toLowerCase().includes(q.toLowerCase())),[q]); const d=makeDetail(selected);
 return <main className="page"><div className="shell"><header className="header"><div className="brandMark">PD</div><div><div className="eyebrow">CLINICAL KNOWLEDGE BASE</div><h1>SKDI 4A Disease Database</h1><p>Diagnosis → pemeriksaan → diagnosis banding → tatalaksana → follow-up → rujukan</p></div></header><section className="hero"><div><span className="pill">SKDI • LEVEL 4A</span><h2>Database penyakit<br/>dokter layanan primer.</h2><p>Basis data 144 entri penyakit tingkat kompetensi 4A dengan tampilan pencarian dan halaman detail klinis.</p></div><div className="heroIcon">4A</div></section><div className="card" style={{marginTop:18}}><div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:10}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari diagnosis…" style={{height:48,border:'1px solid #dce2ec',borderRadius:12,padding:'0 13px',fontSize:14}}/><div className="calcBadge">{filtered.length} / {diseases.length} DIAGNOSIS</div></div></div><div className="skdiLayout" style={{marginTop:18}}><div className="skdiList">{filtered.map((x,i)=><button key={x} className={`skdiItem ${selected===x?'active':''}`} onClick={()=>setSelected(x)}><span className="skdiNo">{diseases.indexOf(x)+1}</span><span><b>{x}</b><small>Kompetensi 4A</small></span></button>)}</div><article className="skdiDetail"><div className="skdiDetailTop"><div><span className="skdiTag">4A</span><h4>{selected}</h4><p>Standar kompetensi layanan primer</p></div><span className="skdiStatus">Verify against current guideline</span></div><div className="skdiSections"><section><h5>1. Diagnosis</h5><p>{d.diagnosis}</p></section><section><h5>2. Pemeriksaan penunjang</h5><p>{d.workup}</p></section><section><h5>3. Diagnosis banding</h5><p>{d.differential}</p></section><section><h5>4. Tatalaksana</h5><p>{d.management}</p></section><section><h5>5. Edukasi & follow-up</h5><p>{d.followUp}</p></section><section className="skdiReferral"><h5>6. Rujuk / red flags</h5><p>{d.referral}</p></section></div><div className="skdiSource"><b>Catatan penting:</b> Level 4A berarti dokter mampu mendiagnosis, melakukan penatalaksanaan secara mandiri dan tuntas untuk penyakit/masalah tersebut dalam konteks kompetensinya. Isi terapi obat, dosis, durasi, kriteria rawat/rujuk harus diverifikasi dengan pedoman nasional/terbaru, formularium dan kondisi individual pasien sebelum dipakai secara klinis.</div></article></div></div></main>;
}
