export type SpectrumEntry = { system:string; level:string; name:string };

export const KKI_2026_SPECTRUM: SpectrumEntry[] = [
  {"system": "Sistem Saraf", "level": "Tuntas", "name": "Tension headache"},
  {"system": "Sistem Saraf", "level": "Tuntas", "name": "Migren"},
  {"system": "Sistem Saraf", "level": "Tuntas", "name": "Vertigo"},
  {"system": "Sistem Saraf", "level": "Tuntas", "name": "Kejang demam"},
  {"system": "Sistem Saraf", "level": "Tuntas", "name": "Tetanus"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Kejang demam komplikata"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Kejang pada neonatus"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Infeksi sitomegalovirus"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Meningitis"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Ensefalitis"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Malaria serebral"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Neuritis vestibularis"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "AIDS dengan komplikasi"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Myelitis"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Poliomielitis"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Rabies"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Ensefalopati"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Koma"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Cluster headache"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "TIA"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Infark serebral"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Hematom intraserebral"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Perdarahan subarachnoid"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Ensefalopati hipertensi"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Meniere’s disease"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Parkinson"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Epilepsi"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Status epilepticus"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Complete spinal transection"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Neurogenic bladder"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Acute medulla compression"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Radicular syndrome"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Hernia nucleus pulposus (HNP)"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Hematom/perdarahan epidural"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Hematom/perdarahan subdural"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Trauma Medula Spinalis"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Fraktur Basis Kranii"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Nyeri nosiseptif, nyeri campur, nyeri rujukan"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Nyeri neuropatik"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Neuropati jeratan"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Neuropati simetris"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Pleksopati"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Peroneal palsy"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Guillain Barre syndrome"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Miastenia gravis"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Krisis miastenik"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Krisis kolinergik"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Amnesia pasca trauma"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Insomnia"},
  {"system": "Sistem Saraf", "level": "Tatalaksana awal dan rujuk", "name": "Gangguan pergerakan lainnya"},
  {"system": "Psikiatri", "level": "Tuntas", "name": "Gangguan psikotik akut dan sementara"},
  {"system": "Psikiatri", "level": "Tuntas", "name": "Skizofrenia tanpa penyulit"},
  {"system": "Psikiatri", "level": "Tuntas", "name": "Skizofrenia dengan penyulit (EPS)"},
  {"system": "Psikiatri", "level": "Tuntas", "name": "Gangguan depresi ringan-sedang"},
  {"system": "Psikiatri", "level": "Tatalaksana awal dan rujuk", "name": "Demensia dengan gejala tambahan"},
  {"system": "Psikiatri", "level": "Tatalaksana awal dan rujuk", "name": "Delirium bukan akibat alkohol/zat psikoaktif"},
  {"system": "Psikiatri", "level": "Tatalaksana awal dan rujuk", "name": "Gangguan skizoafektif"},
  {"system": "Psikiatri", "level": "Tatalaksana awal dan rujuk", "name": "Skizofrenia dengan penyerta"},
  {"system": "Psikiatri", "level": "Tatalaksana awal dan rujuk", "name": "Gangguan afektif bipolar"},
  {"system": "Psikiatri", "level": "Tatalaksana awal dan rujuk", "name": "Gangguan depresi berat, psikotik"},
  {"system": "Psikiatri", "level": "Tatalaksana awal dan rujuk", "name": "Gangguan panik"},
  {"system": "Psikiatri", "level": "Tatalaksana awal dan rujuk", "name": "Gangguan anxietas menyeluruh"},
  {"system": "Sistem Indera — Mata", "level": "Tuntas", "name": "Miopia ringan"},
  {"system": "Sistem Indera — Mata", "level": "Tuntas", "name": "Hipermetropia ringan"},
  {"system": "Sistem Indera — Mata", "level": "Tuntas", "name": "Astigmatisme ringan"},
  {"system": "Sistem Indera — Mata", "level": "Tuntas", "name": "Presbiopia"},
  {"system": "Sistem Indera — Mata", "level": "Tuntas", "name": "Blefaritis akut"},
  {"system": "Sistem Indera — Mata", "level": "Tuntas", "name": "Hordeolum"},
  {"system": "Sistem Indera — Mata", "level": "Tuntas", "name": "Benda asing di konjungtiva"},
  {"system": "Sistem Indera — Mata", "level": "Tuntas", "name": "Konjungtivitis (bakteri, virus, alergi)"},
  {"system": "Sistem Indera — Mata", "level": "Tuntas", "name": "Mata kering"},
  {"system": "Sistem Indera — Mata", "level": "Tuntas", "name": "Episkleritis"},
  {"system": "Sistem Indera — Mata", "level": "Tuntas", "name": "Konjungtivitis"},
  {"system": "Sistem Indera — Mata", "level": "Tuntas", "name": "Perdarahan subkonjungtiva"},
  {"system": "Sistem Indera — Mata", "level": "Tatalaksana awal dan rujuk", "name": "Selulitis preseptal"},
  {"system": "Sistem Indera — Mata", "level": "Tatalaksana awal dan rujuk", "name": "Selulitis orbita"},
  {"system": "Sistem Indera — Mata", "level": "Tatalaksana awal dan rujuk", "name": "Laserasi konjungtiva"},
  {"system": "Sistem Indera — Mata", "level": "Tatalaksana awal dan rujuk", "name": "Perdarahan subkonjungtiva karena trauma"},
  {"system": "Sistem Indera — Mata", "level": "Tatalaksana awal dan rujuk", "name": "Oftalmia neonatorum"},
  {"system": "Sistem Indera — Mata", "level": "Tatalaksana awal dan rujuk", "name": "Trauma kornea"},
  {"system": "Sistem Indera — Mata", "level": "Tatalaksana awal dan rujuk", "name": "Luka bakar kimia/termal"},
  {"system": "Sistem Indera — Mata", "level": "Tatalaksana awal dan rujuk", "name": "Benda asing di kornea"},
  {"system": "Sistem Indera — Mata", "level": "Tatalaksana awal dan rujuk", "name": "Ruptur bola mata"},
  {"system": "Sistem Indera — Mata", "level": "Tatalaksana awal dan rujuk", "name": "Keratitis"},
  {"system": "Sistem Indera — Mata", "level": "Tatalaksana awal dan rujuk", "name": "Ulkus kornea"},
  {"system": "Sistem Indera — Mata", "level": "Tatalaksana awal dan rujuk", "name": "Keratokonjungtivitis sika"},
  {"system": "Sistem Indera — Mata", "level": "Tatalaksana awal dan rujuk", "name": "Xeroftalmia"},
  {"system": "Sistem Indera — Mata", "level": "Tatalaksana awal dan rujuk", "name": "Masalah kornea terkait lensa kontak"},
  {"system": "Sistem Indera — Mata", "level": "Tatalaksana awal dan rujuk", "name": "Keratokonjungtivitis fliktenularis"},
  {"system": "Sistem Indera — Mata", "level": "Tatalaksana awal dan rujuk", "name": "Dakrioadenitis"},
  {"system": "Sistem Indera — Mata", "level": "Tatalaksana awal dan rujuk", "name": "Glaukoma akut"},
  {"system": "Sistem Indera — Mata", "level": "Tatalaksana awal dan rujuk", "name": "Trauma orbit"},
  {"system": "Sistem Indera — Telinga", "level": "Tuntas", "name": "Otitis eksterna"},
  {"system": "Sistem Indera — Telinga", "level": "Tuntas", "name": "Otitis media akut"},
  {"system": "Sistem Indera — Telinga", "level": "Tuntas", "name": "Serumen prop"},
  {"system": "Sistem Indera — Telinga", "level": "Tuntas", "name": "Mabuk perjalanan"},
  {"system": "Sistem Indera — Telinga", "level": "Tuntas", "name": "Benda asing telinga"},
  {"system": "Sistem Indera — Telinga", "level": "Tuntas", "name": "Furunkel pada hidung"},
  {"system": "Sistem Indera — Telinga", "level": "Tatalaksana awal dan rujuk", "name": "Otitis media efusi"},
  {"system": "Sistem Indera — Telinga", "level": "Tatalaksana awal dan rujuk", "name": "Otitis media kronik"},
  {"system": "Sistem Indera — Telinga", "level": "Tatalaksana awal dan rujuk", "name": "Trauma aurikuler"},
  {"system": "Sistem Indera — Telinga", "level": "Tatalaksana awal dan rujuk", "name": "Inflamasi aurikuler"},
  {"system": "Sistem Indera — Hidung", "level": "Tuntas", "name": "Rhinitis akut"},
  {"system": "Sistem Indera — Hidung", "level": "Tuntas", "name": "Sinusitis akut"},
  {"system": "Sistem Indera — Hidung", "level": "Tuntas", "name": "Epistaxis anterior"},
  {"system": "Sistem Indera — Hidung", "level": "Tuntas", "name": "Benda asing hidung"},
  {"system": "Sistem Indera — Hidung", "level": "Tatalaksana awal dan rujuk", "name": "Rhinitis kronik"},
  {"system": "Sistem Indera — Hidung", "level": "Tatalaksana awal dan rujuk", "name": "Epistaksis posterior"},
  {"system": "Sistem Respirasi", "level": "Tuntas", "name": "Flu musiman (seasonal flu)"},
  {"system": "Sistem Respirasi", "level": "Tuntas", "name": "Pertusis"},
  {"system": "Sistem Respirasi", "level": "Tuntas", "name": "Difteria"},
  {"system": "Sistem Respirasi", "level": "Tuntas", "name": "Faringitis"},
  {"system": "Sistem Respirasi", "level": "Tuntas", "name": "Tonsilitis"},
  {"system": "Sistem Respirasi", "level": "Tuntas", "name": "Laringitis"},
  {"system": "Sistem Respirasi", "level": "Tuntas", "name": "Asma bronkial"},
  {"system": "Sistem Respirasi", "level": "Tuntas", "name": "Bronkitis akut"},
  {"system": "Sistem Respirasi", "level": "Tuntas", "name": "Bronkiolitis"},
  {"system": "Sistem Respirasi", "level": "Tuntas", "name": "TB paru tanpa komplikasi"},
  {"system": "Sistem Respirasi", "level": "Tuntas", "name": "TB Laten (Latent Tuberculosis Infection)"},
  {"system": "Sistem Respirasi", "level": "Tuntas", "name": "Rujuk balik MDR TB"},
  {"system": "Sistem Respirasi", "level": "Tuntas", "name": "Gawat napas (respiratory distress)"},
  {"system": "Sistem Respirasi", "level": "Tuntas", "name": "Rhinitis"},
  {"system": "Sistem Respirasi", "level": "Tuntas", "name": "Benda asing di hidung"},
  {"system": "Sistem Respirasi", "level": "Tuntas", "name": "COVID-19"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Flu burung"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Laringitis kronik"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Sindroma Croup"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Trakeitis"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Aspirasi"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Benda asing di trakea"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Status asmatikus"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Bronkitis kronis"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Bronkopneumonia"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Pneumonia aspirasi"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "HAP/VAP"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Pneumonia virus (SARS, H1N1, H5N1)"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Pneumonia jamur"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Pneumonia parasit"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Emboli paru"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Efusi pleura masif"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "PPOK stabil"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "PPOK eksaserbasi"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Edema paru"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Pneumotoraks"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Tension pneumotoraks"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Hematotoraks"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "Gagal napas"},
  {"system": "Sistem Respirasi", "level": "Tatalaksana awal dan rujuk", "name": "ARDS"},
  {"system": "Sistem Kardiovaskuler", "level": "Tuntas", "name": "Syok hipovolemik"},
  {"system": "Sistem Kardiovaskuler", "level": "Tuntas", "name": "Hipertensi esensial"},
  {"system": "Sistem Kardiovaskuler", "level": "Tuntas", "name": "Rujuk balik hipertensi sekunder"},
  {"system": "Sistem Kardiovaskuler", "level": "Tatalaksana awal dan rujuk", "name": "Syok (septik, kardiogenik, neurogenik)"},
  {"system": "Sistem Kardiovaskuler", "level": "Tatalaksana awal dan rujuk", "name": "Sindrom koroner akut"},
  {"system": "Sistem Kardiovaskuler", "level": "Tatalaksana awal dan rujuk", "name": "Gagal jantung akut"},
  {"system": "Sistem Kardiovaskuler", "level": "Tatalaksana awal dan rujuk", "name": "Cardiorespiratory arrest"},
  {"system": "Sistem Kardiovaskuler", "level": "Tatalaksana awal dan rujuk", "name": "Bradikardi simtomatik"},
  {"system": "Sistem Kardiovaskuler", "level": "Tatalaksana awal dan rujuk", "name": "Takikardi"},
  {"system": "Sistem Kardiovaskuler", "level": "Tatalaksana awal dan rujuk", "name": "Fibrilasi atrial"},
  {"system": "Sistem Kardiovaskuler", "level": "Tatalaksana awal dan rujuk", "name": "Fibrilasi ventrikular"},
  {"system": "Sistem Kardiovaskuler", "level": "Tatalaksana awal dan rujuk", "name": "Atrial flutter"},
  {"system": "Sistem Kardiovaskuler", "level": "Tatalaksana awal dan rujuk", "name": "Kor pulmonale akut"},
  {"system": "Sistem Kardiovaskuler", "level": "Tatalaksana awal dan rujuk", "name": "Spell hypoxic"},
  {"system": "Sistem Kardiovaskuler", "level": "Tatalaksana awal dan rujuk", "name": "Krisis hipertensi"},
  {"system": "Sistem Kardiovaskuler", "level": "Tatalaksana awal dan rujuk", "name": "Trauma vaskular"},
  {"system": "Sistem Kardiovaskuler", "level": "Tatalaksana awal dan rujuk", "name": "Radang dinding jantung"},
  {"system": "Sistem Kardiovaskuler", "level": "Tatalaksana awal dan rujuk", "name": "Obstructive Sleep Apnea"},
  {"system": "Sistem Kardiovaskuler", "level": "Tatalaksana awal dan rujuk", "name": "Kelainan jantung kongenital"},
  {"system": "Sistem Kardiovaskuler", "level": "Tatalaksana awal dan rujuk", "name": "Gagal jantung"},
  {"system": "Sistem Kardiovaskuler", "level": "Tatalaksana awal dan rujuk", "name": "Blue Child"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Kandidiasis mulut"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Ulkus mulut (aptosa, herpes)"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Parotitis"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Infeksi pada umbilikus"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Gastritis"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Gastroenteritis (termasuk kolera, giardiasis)"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Refluks gastroesofagus"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Demam tifoid"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Intoleransi makanan"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Alergi makanan"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Keracunan makanan"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Penyakit Cacingan"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Strongiloidiasis"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Askariasis"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Skistosomiasis"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Taeniasis"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Trichuriasis"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Oxyuriasis"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Hepatitis A"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Rujuk Balik Hepatitis C"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Disentri basiler, amuba"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tuntas", "name": "Hemoroid grade 1-2"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tatalaksana awal dan rujuk", "name": "Lesi korosif esofagus"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tatalaksana awal dan rujuk", "name": "Hernia strangulata/inkarserata"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tatalaksana awal dan rujuk", "name": "Peritonitis"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tatalaksana awal dan rujuk", "name": "Perforasi usus"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tatalaksana awal dan rujuk", "name": "Ileus obstruksi"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tatalaksana awal dan rujuk", "name": "Ileus paralitik"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tatalaksana awal dan rujuk", "name": "Apendisitis akut"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tatalaksana awal dan rujuk", "name": "Abses apendiks"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tatalaksana awal dan rujuk", "name": "Demam tifoid dengan komplikasi"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tatalaksana awal dan rujuk", "name": "Perdarahan gastrointestinal"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tatalaksana awal dan rujuk", "name": "Keracunan racun alam"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tatalaksana awal dan rujuk", "name": "Keracunan insektisida"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tatalaksana awal dan rujuk", "name": "Hemoroid grade3"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tatalaksana awal dan rujuk", "name": "Botulisme"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tatalaksana awal dan rujuk", "name": "Kolesistitis"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tatalaksana awal dan rujuk", "name": "Pankreatitis"},
  {"system": "Sistem Gastrointestinal, Hepatobilier, dan Pankreas", "level": "Tatalaksana awal dan rujuk", "name": "Intususepsi"},
  {"system": "Sistem Ginjal dan Saluran Kemih", "level": "Tuntas", "name": "Sistitis"},
  {"system": "Sistem Ginjal dan Saluran Kemih", "level": "Tuntas", "name": "Pielonefritis tanpa komplikasi"},
  {"system": "Sistem Ginjal dan Saluran Kemih", "level": "Tuntas", "name": "Fimosis"},
  {"system": "Sistem Ginjal dan Saluran Kemih", "level": "Tuntas", "name": "Parafimosis"},
  {"system": "Sistem Ginjal dan Saluran Kemih", "level": "Tuntas", "name": "Gonore"},
  {"system": "Sistem Ginjal dan Saluran Kemih", "level": "Tuntas", "name": "Uretritis gonore tanpa komplikasi"},
  {"system": "Sistem Ginjal dan Saluran Kemih", "level": "Tuntas", "name": "Uretritis non-gonore tanpa komplikasi"},
  {"system": "Sistem Ginjal dan Saluran Kemih", "level": "Tuntas", "name": "Infeksi saluran kemih"},
  {"system": "Sistem Ginjal dan Saluran Kemih", "level": "Tuntas", "name": "Penyakit ginjal diabetik ringan"},
  {"system": "Sistem Ginjal dan Saluran Kemih", "level": "Tatalaksana awal dan rujuk", "name": "Acute kidney injury"},
  {"system": "Sistem Ginjal dan Saluran Kemih", "level": "Tatalaksana awal dan rujuk", "name": "Torsio testis"},
  {"system": "Sistem Ginjal dan Saluran Kemih", "level": "Tatalaksana awal dan rujuk", "name": "Ruptur uretra"},
  {"system": "Sistem Ginjal dan Saluran Kemih", "level": "Tatalaksana awal dan rujuk", "name": "Ruptur kandung kencing"},
  {"system": "Sistem Ginjal dan Saluran Kemih", "level": "Tatalaksana awal dan rujuk", "name": "Ruptur ginjal"},
  {"system": "Sistem Ginjal dan Saluran Kemih", "level": "Tatalaksana awal dan rujuk", "name": "Priapismus"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Antenatal care terpadu berdasarkan buku KIA"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Emesis gravidarum"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Abortus Insipien kurang dari 13 minggu"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Abortus inkomplit kurang dari 13 minggu"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Abortus komplit"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Kecacingan pada kehamilan"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Infeksi saluran kemih pada kehamilan"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Discharge vagina pada kehamilan"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Malaria pada kehamilan tanpa komplikasi"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Tuberkulosis pada kehamilan"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Infeksi saluran nafas atas pada kehamilan"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Gastroenteritis akut pada kehamilan"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Pertolongan Persalinan Normal"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Hipotonia Uteri"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Ruptur perineum derajat 1-2"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Retensio plasenta"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Keluarga berencana masa nifas"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Lesi pra kanker serviks (4)"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Infeksi virus Herpes tipe 2"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Sifilis/ Ulkus durum"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Vulvovaginitis candida"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Vaginosis bakterialis"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Servisitis"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Sindrom duh (discharge) genital gonore dan non gonore"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Infeksi saluran kemih bagian bawah"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Vulvitis"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Vaginitis"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Kehamilan normal"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Aborsi spontan komplit"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Anemia defisiensi besi pada kehamilan"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Ruptur perineum tingkat 1-2"},
  {"system": "Sistem Reproduksi", "level": "Tuntas", "name": "Mastitis"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Hiperemesis gravidarum"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Kehamilan ektopik terganggu"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Abortus iminen"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Abortus inkomplit <13 minggu"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Mola hidatidosa"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Partus prematurus iminen"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Solusio plasenta"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Plasenta previa"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Eklampsia"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Sindrom HELLP"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Gawat janin"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Ketuban pecah dini"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Malpresentasi"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Kala I memanjang"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Partus tak maju"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Partus lama"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Kala II tidak maju"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Prolaps tali pusat"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Persalinan preterm"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Disproporsi kepala panggul"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Distosia bahu"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Atonia uteri"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Ruptur perineum derajat 3–4"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Laserasi vagina/serviks"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Retensio sisa plasenta"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Inversio uteri"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Hematoma vulva"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Perdarahan uterus abnormal berat"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Torsi/ruptur kista ovarium"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Abses kelenjar Bartolini"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Vulnus pada vulva/vagina"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Toxoplasmosis"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Kista Bartolini"},
  {"system": "Sistem Reproduksi", "level": "Tatalaksana awal dan rujuk", "name": "Infertil wanita dan pria"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tuntas", "name": "Diabetes melitus tipe 1 tanpa komplikasi"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tuntas", "name": "Diabetes mellitus tipe 2"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tuntas", "name": "Hipoglikemia ringan"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tuntas", "name": "Rujuk balik Hipertiroid"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tuntas", "name": "Rujuk balik Goiter"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tuntas", "name": "Defisiensi vitamin"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tuntas", "name": "Defisiensi mineral"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tuntas", "name": "Dislipidemia"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tuntas", "name": "Hiperurisemia"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tuntas", "name": "Sindroma metabolic"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tuntas", "name": "Stunting (perawakan pendek)"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tuntas", "name": "Malnutrisi energi-protein"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tuntas", "name": "Obesitas"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tatalaksana awal dan rujuk", "name": "Ketoasidosis diabetikum"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tatalaksana awal dan rujuk", "name": "Ulkus Gangrenosa"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tatalaksana awal dan rujuk", "name": "Hiperglikemia hiperosmolar non ketotik"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tatalaksana awal dan rujuk", "name": "Hipoglikemia berat"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tatalaksana awal dan rujuk", "name": "Tirotoksikosis"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tatalaksana awal dan rujuk", "name": "Cushing’s disease"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tatalaksana awal dan rujuk", "name": "Krisis adrenal"},
  {"system": "Sistem Endokrin, Metabolik, dan Nutrisi", "level": "Tatalaksana awal dan rujuk", "name": "Gangguan elektrolit karena metabolik"},
  {"system": "Sistem Hemato dan Imunologi", "level": "Tuntas", "name": "Anemia defisiensi vitamin/mineral (Besi, B12)"},
  {"system": "Sistem Hemato dan Imunologi", "level": "Tuntas", "name": "Demam dengue, DHF"},
  {"system": "Sistem Hemato dan Imunologi", "level": "Tuntas", "name": "Malaria tanpa komplikasi"},
  {"system": "Sistem Hemato dan Imunologi", "level": "Tuntas", "name": "Leptospirosis (tanpa komplikasi)"},
  {"system": "Sistem Hemato dan Imunologi", "level": "Tuntas", "name": "Lupus eritematosus sistemik ringan dan remisi (rujuk balik)"},
  {"system": "Sistem Hemato dan Imunologi", "level": "Tuntas", "name": "Reaksi anafilaktik"},
  {"system": "Sistem Hemato dan Imunologi", "level": "Tuntas", "name": "Limfadenitis"},
  {"system": "Sistem Hemato dan Imunologi", "level": "Tatalaksana awal dan rujuk", "name": "Leishmaniasis dan tripanosomiasi"},
  {"system": "Sistem Hemato dan Imunologi", "level": "Tatalaksana awal dan rujuk", "name": "Keganasan / kanker"},
  {"system": "Sistem Hemato dan Imunologi", "level": "Tatalaksana awal dan rujuk", "name": "Leptospirosis"},
  {"system": "Sistem Muskuloskeletal", "level": "Tuntas", "name": "Artritis Gout"},
  {"system": "Sistem Muskuloskeletal", "level": "Tuntas", "name": "Artritis Rheumatoid rujuk balik"},
  {"system": "Sistem Muskuloskeletal", "level": "Tuntas", "name": "Ulkus ringan pada tungkai"},
  {"system": "Sistem Muskuloskeletal", "level": "Tuntas", "name": "Lipoma superfisial"},
  {"system": "Sistem Muskuloskeletal", "level": "Tuntas", "name": "Luka akut"},
  {"system": "Sistem Muskuloskeletal", "level": "Tuntas", "name": "Ulkus pada tungkai"},
  {"system": "Sistem Muskuloskeletal", "level": "Tuntas", "name": "Lipoma"},
  {"system": "Sistem Muskuloskeletal", "level": "Tuntas", "name": "Osteoartritis grade 1 dan 2"},
  {"system": "Sistem Muskuloskeletal", "level": "Tuntas", "name": "Nyeri sendi non spesifik"},
  {"system": "Sistem Muskuloskeletal", "level": "Tuntas", "name": "Inflamasi ringan Otot, tendon dan ligamen"},
  {"system": "Sistem Muskuloskeletal", "level": "Tatalaksana awal dan rujuk", "name": "Osteoartritis grade 3 dan 4"},
  {"system": "Sistem Muskuloskeletal", "level": "Tatalaksana awal dan rujuk", "name": "Artritis septik"},
  {"system": "Sistem Muskuloskeletal", "level": "Tatalaksana awal dan rujuk", "name": "Artritis Psoriatik"},
  {"system": "Sistem Muskuloskeletal", "level": "Tatalaksana awal dan rujuk", "name": "Fraktur terbuka/tertutup"},
  {"system": "Sistem Muskuloskeletal", "level": "Tatalaksana awal dan rujuk", "name": "Ruptur tendon Achilles"},
  {"system": "Sistem Muskuloskeletal", "level": "Tatalaksana awal dan rujuk", "name": "Osteomielitis"},
  {"system": "Sistem Muskuloskeletal", "level": "Tatalaksana awal dan rujuk", "name": "Sprain (ankle and muscle)"},
  {"system": "Sistem Muskuloskeletal", "level": "Tatalaksana awal dan rujuk", "name": "Ruptur ligamen lutut"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Varisela"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Herpes Zoster tanpa komplikasi"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Morbili/ campak tanpa komplikasi"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Herpes simpleks tanpa komplikasi"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Hand, mouth and foot disease"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Impetigo"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Ektima"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Folikulitis"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Paronikia"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Lepra/Kusta Tanpa Komplikasi"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Sifilis primer dan laten"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Frambusia"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Dermatofitosis /TINEA"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Kandidosis kutis"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "In growing toenail"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Hidradenitis supuratif"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Rosasea"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Skabies"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Cutaneus larva migran"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Filariasis tanpa komplikasi"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Dermatitis / Ecxema (Termasuk atopik, seboroik, kontak, venata, perioral)"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Psoriasis vulgaris ringan"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Miliaria"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Akne vulgaris"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Urtikaria"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Clavus"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Kalus"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Vulnus laceratum, punctum"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Luka bakar derajat 1"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Melasma"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Pediculosis capitis, pubis"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Reaksi gigitan serangga"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Lentigo"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Hiperpigmentasi pasca inflamasi"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Hipopigmentasi pasca inflamasi"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Veruka vulgaris"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Moluskum kontagiosum"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Eritrasma"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Erisipelas"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Skrofuloderma"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Pitiriasis alba"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Pitiriasis rosea"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tuntas", "name": "Exanthematous drug"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tatalaksana awal dan rujuk", "name": "Eritroderma"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tatalaksana awal dan rujuk", "name": "Toxic epidermal necrolysis (TEN)"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tatalaksana awal dan rujuk", "name": "Sindrom Stevens-Johnson (SSJ)"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tatalaksana awal dan rujuk", "name": "Drug Reaction Eosinophilia and Systemic Symptoms (DRESS)"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tatalaksana awal dan rujuk", "name": "Acute Generalized Exanthematous Pustulosis (AGEP)"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tatalaksana awal dan rujuk", "name": "Angioedema"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tatalaksana awal dan rujuk", "name": "Vulnus perforatum/penetratum"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tatalaksana awal dan rujuk", "name": "Luka bakar derajat 2 >10%"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tatalaksana awal dan rujuk", "name": "Keganasan pada kulit"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tatalaksana awal dan rujuk", "name": "Luka bakar derajat 3"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tatalaksana awal dan rujuk", "name": "Luka akibat trauma dingin"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tatalaksana awal dan rujuk", "name": "Luka akibat bahan kimia"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tatalaksana awal dan rujuk", "name": "Luka akibat sengatan listrik"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tatalaksana awal dan rujuk", "name": "Herpes zoster dengan komplikasi"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tatalaksana awal dan rujuk", "name": "Herpes simpleks dengan komplikasi"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tatalaksana awal dan rujuk", "name": "Morbili/ campak dengan komplikasi"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tatalaksana awal dan rujuk", "name": "Sifilis Tersier"},
  {"system": "Sistem Kulit dan Integumen", "level": "Tatalaksana awal dan rujuk", "name": "Psoriasis vulgaris sedang dan berat"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tuntas", "name": "Kekerasan tumpul"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tuntas", "name": "Kekerasan tajam"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tuntas", "name": "Cedera dan kematian akibat kecelakaan lalu lintas"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tuntas", "name": "Thanatologi"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tuntas", "name": "Pemeriksaan luar jenazah"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tuntas", "name": "Surat Keterangan Kematian"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tatalaksana awal dan rujuk", "name": "Kejahatan terhadap kesusilaan"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tatalaksana awal dan rujuk", "name": "Luka tembak"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tatalaksana awal dan rujuk", "name": "Luka listrik dan petir"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tatalaksana awal dan rujuk", "name": "Trauma kimia"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tatalaksana awal dan rujuk", "name": "Barotrauma"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tatalaksana awal dan rujuk", "name": "Trauma suhu"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tatalaksana awal dan rujuk", "name": "Asfiksia"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tatalaksana awal dan rujuk", "name": "Tenggelam"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tatalaksana awal dan rujuk", "name": "Toksikologi forensik"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tatalaksana awal dan rujuk", "name": "Dead on Arrival (DOA)"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tatalaksana awal dan rujuk", "name": "Identifikasi forensik"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tatalaksana awal dan rujuk", "name": "Pengguguran kandungan"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tatalaksana awal dan rujuk", "name": "Kematian mendadak"},
  {"system": "Ilmu Kedokteran Forensik dan Medikolegal", "level": "Tatalaksana awal dan rujuk", "name": "Pembunuhan anak sendiri"},
  {"system": "Anak", "level": "Tuntas", "name": "Stunting"},
  {"system": "Anak", "level": "Tuntas", "name": "Demam Dengue"},
  {"system": "Anak", "level": "Tatalaksana awal dan rujuk", "name": "Gagal Nafas"},
  {"system": "Anak", "level": "Tatalaksana awal dan rujuk", "name": "Syok Dengue"},
];
